server:
    port: 8085
    servlet:
        context-path: /resena
        
spring:
    #mandatory-file-encoding: UTF-8
    http:
        encoding:
            charset: UTF-8
            enabled: true
    datasource:
        url: jdbc:mysql://127.0.0.1/videoJuegos?serverTimezone=GMT-6
        driver: com.mysql.jdbc.Driver
        username: admin
        password: admin
        testWhileIdle: true
        initialize: true
        hikari:
            maximum-pool-size: 10
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl